### ISSUE TITLE
#4: Get feedback updates

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#11]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
1) Create a new branch named `feat/get-feedback-updates`
2) Add scheduled Celery tasks that run every predefined number of seconds and fetches approvals or revisions for current user.
3) Notify him about on telegram

**Comment by emarc99** [comment]
Let me work on this.

**Comment by emmz3230** [comment]
hi 
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.


i will like to work on this through your onboarding process and me learn django it will be helpful to use my skill on a live project like  this.

**Comment by emarc99** [comment]
Thank you. Starting work right away.

**Comment by djeck1432** [comment]
@emarc99 Hi, any updates?

**Comment by emarc99** [comment]
Hello, please gimme till today's end.

**Comment by iamnovichek** [comment]
@emarc99 any updates?

**Comment by emarc99** [comment]
I am still working, should make a draft PR, at least, today.

**Comment by iamnovichek** [comment]
> I am still working, should make a draft PR, at least, today. 

Hi @emarc99 . You have time till today. Otherwise you will be unassigned.

**Comment by ShantelPeters** [comment]
Hello @iamnovichek please can i work on this

**Comment by emarc99** [comment]
wow, is the day really over?

**Comment by djeck1432** [comment]
I think he is in context of the light day, in Europe it's night almost.
Feel free to apply to another issue, but be ready to prepare at least draft PR during 12 hours.

**Comment by jaykayudo** [comment]
@iamnovichek Can i Work on this?

### How i will tackle this?
- I will create a new branch (my PR branch ) `feat/get-feedback-updates` for  my changes
- I will add scheduled Celery tasks that run every predefined number of seconds and fetches approvals or revisions for current user using celery-beat
- I will add a functionality notify the user via telegram using the already provided api

I've read all rules and I promise that I won't use ChatGPT while applying to this issue

**Comment by jaykayudo** [comment]
Thanks @iamnovichek . On it
