### ISSUE TITLE
#6: Refactor some code blocks

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#22]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Use `Template string` in `telegram/bot.py` to secure bot - user interaction (all messages the bot sends)
3) Remove `response.ok` within `if` statement and move the code inside 1 indentation level left in `utils.py`

**Comment by Judah04** [comment]
@iamnovichek I’ll secure the interactions using the string.Template library, remove response.ok within the if statement and move code left out of indentation. Finally, I'll simplify the conditional in line 107 of utils.py using if not all().

**Comment by jaykayudo** [comment]
@iamnovichek Can i work on this?
I will secure the user interaction using Template in the string library,
I will remove the `response.ok` from within the if statement and update the indentation level of the code.
I will refactor the code in the specified utils file section using `if not all()`
I've read all rules and I promise that I won't use ChatGPT while applying to this issue

**Comment by mexes20** [comment]
@iamnovichek can I be assigned to work on this?

I'll open a draft PR within 12 hours of assignment.

**Comment by ShantelPeters** [comment]
Hello @iamnovichek can i please be assigned to this issue

**Comment by iamnovichek** [comment]
> @iamnovichek Can i work on this?
> I will secure the user interaction using Template in the string library,
> I will remove the `response.ok` from within the if statement and update the indentation level of the code.
> I will refactor the code in the specified utils file section using `if not all()`
> I've read all rules and I promise that I won't use ChatGPT while applying to this issue

@jaykayudo you are assigned to another task. Finish your task before applying to another one )

**Comment by raizo07** [comment]
Hey @iamnovichek I'll like to be assigned to work on this.

if not `all()` to refactor the specified code and remove the `response.ok` from within the conditional statement after which I'll update the indentation level of the code.

**Comment by godekina** [comment]
@iamnovichek can I be assigned to work on this issue? I am a Python developer and'll conclude the task within 24 hours of being assigned. I have read through the contribution guidelines, I understand the task required and will not use chatGPT for this.

To refactor the codebase, I will:
- secure the messages the bot sends by modifying the telegram/bot.py file using the template string.
 - modify the utils.py using the if statement with a not all() boolean

**Comment by iamnovichek** [comment]
Guys, please read the guideline before applying to the issue

**Comment by SYLVIANNORUKA** [comment]
I'd like to take this issue.I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by Joe-joe25** [comment]
Can I take on this issue? I'd love to help refactor and secure the bot interactions

**Comment by mimisavage** [comment]
Could I take on this issue?

**Comment by Akshola00** [comment]
Can I take this issue?

**Comment by iamnovichek** [comment]
@godekina assigned

**Comment by godekina** [comment]
@iamnovichek kindly review PR made at: https://github.com/KostCode-Organization/hackathon_bot/pull/27

**Comment by VitalinaMykoliuk** [comment]
"Pizza makes people happy"  
Hi, I would like to take on this task!

**Comment by iamnovichek** [comment]
@VitalinaMykoliuk assigned
