### ISSUE TITLE
#7: Add dynamic setting tasks deadline for repository

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#23]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Add `time_limit` field to `Repository` model
3) Update migrations
4) Update `Repository` model class docstring

**Comment by Judah04** [comment]
@iamnovichek I would add a time_limit field to the Repository class in model.py, ensure it stores the task deadline, then update migrations and docstring accordingly.

**Comment by Judah04** [comment]
@iamnovichek I've read all rules and I promise that I won't use ChatGPT while applying to this issue.
To solve this issue, I would add a time_limit field to the Repository class in models.py to store the task deadline, then update migrations and docstring accordingly.

**Comment by ghost** [comment]
@iamnovichek I have some level of experience using python. kindly assign me the above task.
I've gone through the guidelines and I promise that I won't use ChatGPT while applying to this issue.
 
To solve the above task, I will add a `time_limit` field to the repository class in `models.py` to store the task deadline and also include appropriate validation for deadlines, migrations will be updated to reflect the new `time_limit` field and i will modify the class docstring to contain the purpose of the `time_limit` field.

**Comment by iamnovichek** [comment]
> @iamnovichek I have some level of experience using python. kindly assign me the above task. I've gone through the guidelines and I promise that I won't use ChatGPT while applying to this issue.
> 
> To solve the above task, I will add a `time_limit` field to the repository class in `models.py` to store the task deadline and also include appropriate validation for deadlines, migrations will be updated to reflect the new `time_limit` field and i will modify the class docstring to contain the purpose of the `time_limit` field.

Hi. Idk why but I cannot even tag you. It's likely GitHub problem. Could you pls write one more comment so hopefully It's gonna work?

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by 0xBinayak** [comment]
I've read all rules and I promisse that I won't use ChatGPT while applying to this issue.
Can I jump on this task? ithik i can do this task  reasonably fast

**Comment by djeck1432** [comment]
I hope you will do it fast and can start working on integration tests 😏
