### ISSUE TITLE
#8: Attach hyperlink to each issue

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#24]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Create `get_hyperlink` function in `utils.py` that returns a hyperlink string to the current issue
3) Attach the link to each issue in `send_available_issues` function [here](https://github.com/KostCode-Organization/hackathon_bot/blob/main/tracker/telegram/bot.py#L132)

**Comment by Judah04** [comment]
@iamnovichek I would create a get_hyperlink function in util.py to generate issue links and modify the send_available_issues function to incorporate clickable hyperlinks for each issue in the Telegram message.

**Comment by petersdt** [comment]
Hi @iamnovichek  i have some level of experience using python. kindly assign me the above task. I have gone through the guideline an would make a PR <=12hrs stipulated time.

Psuedo approach to solve the above task:
- i will create a `get_hyperlink` function at: [utilis.py](https://github.com/KostCode-Organization/hackathon_bot/blob/main/tracker/utils.py)
- import function created in utils into [`send_avaliable_issues`](https://github.com/KostCode-Organization/hackathon_bot/blob/main/tracker/telegram/bot.py#L132) 
- I will modify the message templates


kindly assign me

**Comment by Chukwuemeka-James** [comment]
"I've read all rules and I promisse that I won't use ChatGPT while applying to this issue". I will create a get_hyperlink function in the util.py file to generate links for issues and integrate it into the send_available_issues function to add a clickable link to each issue in notifications.

**Comment by Chukwuemeka-James** [comment]
"I've read all rules and I promisse that I won't use ChatGPT while applying to this issue". I will create a get_hyperlink function in the util.py file to generate links for issues and integrate it into the send_available_issues function to add a clickable link to each issue.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by od-hunter** [comment]
Hi @iamnovichek , can I be assigned this issue please? I've read all rules and I promisse that I won't use ChatGPT while applying to this issue.

I’ll create get_hyperlink function in utils.py.

**Comment by iamnovichek** [comment]
@od-hunter assigned

**Comment by od-hunter** [comment]
> @od-hunter assigned

Thank you ser @iamnovichek

**Comment by CollinsC1O** [comment]
May I try my hand at this?

**Comment by od-hunter** [comment]
@iamnovichek am I supposed to do this issue in 2 hours? You assigned me I acknowledged and then you unassign me?

**Comment by iamnovichek** [comment]
> @iamnovichek am I supposed to do this issue in 2 hours? You assigned me I acknowledged and then you unassign me?

24 hours passed after I assigned you

**Comment by od-hunter** [comment]
> > @iamnovichek am I supposed to do this issue in 2 hours? You assigned me I acknowledged and then you unassign me?
> 
> 24 hours passed after I assigned you

but I just saw it and acknowledged 7 hours ago and then you unassigned me 5 hours later when I was already working on it.

**Comment by codebestia** [comment]
Can i work on this?

## How i will tackle this
- I will enclose the issue title with a hyperlink tag linking to the issue page for any bot command that involves receiving an issue title.
- I will test manually to ensure the link is added properly and does not break any code.

I've read all rules and I promise that I won't use ChatGPT while applying to this issue

**Comment by Aditya-040** [comment]
Can I start working on this?

**Comment by emarc99** [comment]
I've read all rules and I promisse that I won't use ChatGPT while applying to this issue.

Let me do this.

**Comment by pheobeayo** [comment]
May I pick this up?

**Comment by iamnovichek** [comment]
@codebestia assigned
