### ISSUE TITLE
#9 Use aoigram html.unparse for escape html

### ISSUE THREAD

**Issue by Avazart** [KostCode-Organization/hackathon_bot#26]
https://github.com/KostCode-Organization/hackathon_bot/blob/0b3a54d17a1a816e280dec0652c952a7ad3fe161/tracker/telegram/bot.py#L116C1-L128C6

```
from aiogram import html

code = "if  a>b: return a<<1;"
print(html.unparse(code))

```
https://github.com/aiogram/aiogram/blob/acf52f468cae79b3511c2939cf39a801fa47f9f3/aiogram/utils/text_decorations.py#L82

Additionally: https://t.me/aiogramua/55309/151496

**Comment by od-hunter** [comment]
Hi @Avazart can I contribute to this please
