### ISSUE TITLE
#9: Check contributor's assigned issues

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#29]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
 2) For this issue you should use GitHub API
 3) Create `get_contributor_issues` function in `tracker/utils.py` that recieves a github username as an argument and returns all issues the user is assigned to
 4) Create a telegram command `get_cotributor_tasks` that recieves a github username as an argument and returns all open issues assigned to this username with a label that matches "ODHack" regex
 5) Provide some screenshots to prove that the task works correctly

**Comment by vitaliypopel** [comment]
I've read all rules and I promisse that I won't use ChatGPT while applying to this issue. And I wanna get this task to add new `get_contributor_issues` to `tracker/utils`, and test it out

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue. I've read all rules and I promisse that I won't use ChatGPT while applying to this issue

**Comment by ikemHood** [comment]
Hey @iamnovichek, I can help out with this,
I've read all rules and I promisse that I won't use ChatGPT while applying to this issue.
I have a good background with backend and Python

**Comment by iamnovichek** [comment]
@BrunoAmbricca any progress? pls create at least a draft PR

**Comment by BrunoAmbricca** [comment]
Yes yes, I´ll create the draft PR shortly.
