### ISSUE TITLE
#10: Use aoigram html.unparse for escape html

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#30]
Issue author - [here](https://github.com/Avazart)
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Use `html.unparse(code)` in `tracker/telegram/bot.py` [here](https://github.com/KostCode-Organization/hackathon_bot/blob/main/tracker/telegram/bot.py#L116)
3) Provide some screenshots that your changes work as expected

**Comment by emarc99** [comment]
I've read all rules and I promisse that I won't use ChatGPT while applying to this issue

I will clone the repo
import aoigram's html.unparse
Edit def escape_html() in tracker/telegram/bot.py to return text using html.unparse()
Test with sample text containing html symbols/tags

After test pass, use isort & black on bot.py

**Comment by iamnovichek** [comment]
@emarc99 assigned

**Comment by emarc99** [comment]
Thank you.
