### ISSUE TITLE
#11: Add role choices

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#35]
1) Read guideline before applying [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Create new file named `choices.py` in `tracker/`
3) Create new class named `Roles` that inherits Django's `models.TextChoices` class
4) Add `project-lead` and `contributor`  roles

**Comment by Abeeujah** [comment]
Hi, I've gone through the Guidelines, the task seems pretty detailed as well, I'd love to work on this task, ETA 6hrs

**Comment by iamnovichek** [comment]
> I've gone through the Guidelines

No you lie :(

**Comment by Abeeujah** [comment]
Hi, I've gone through the Guidelines, the task seems pretty detailed as well, I'd love to work on this task,

- I'd create the file choices.py in the tracker directory
- Create a new class named Roles that inherits models.TextChoices class
- The roles to be added are project-lead and contributor

Pizza makes people happy
ETA 6hrs

**Comment by iamnovichek** [comment]
@Abeeujah assigned
