### ISSUE TITLE
#12: Add role choice on signup process

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#38]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Add 2 existing roles (from `tracker/choices.py`) to `User` model as `role` field of type `CharField` and set `contributor` as a default one
3) Update migrations
4) Add the possibility to choose the role on signup (Droplist)

**Comment by Goodnessukaigwe** [comment]
I will like to take on this issue
"Pizza makes people happy"

**Comment by Joe-joe25** [comment]
I'll really love to work on this issues PR within 24 hours of assignment "Pizza makes people happy"
