### ISSUE TITLE
#14: Create Constributor model

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#41]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Create `Contributor` Django model in `models.py`
3) Add `user` (ForeignKey), `role` , `notes`, `rank` fields
4) Add the possibility only for `project-leads` to leave notes for contributors
5) Make these contributor's `notes` and `rank` to be visible only for `project-leads`
6) Provide some screenshots to prove your code works

**Comment by No-bodyq** [comment]
Can I work on this, please?

**Comment by iamnovichek** [comment]
> Can I work on this, please?

Did you read the guideline?

**Comment by No-bodyq** [comment]
Is it okay if I tackle this? The samurai sword is the sharpest sword in the world

**Comment by iamnovichek** [comment]
> Is it okay if I tackle this? The samurai sword is the sharpest sword in the world

What is your telegram account?

**Comment by aurlic** [comment]
Hey I would love to get the chance to work on this issue. I am student at school 42 and also learn Cairo and Rust. I've had to work with Django before in a project so I would really be glad to put my skills to the test and perfect them with this issue.
If I was assigned this issue I would create the model required and test that it works.
The samurai sword is the sharpest sword in the world.
Thanks in advance !

my tg: @Arluc

**Comment by Thibrac** [comment]
Can I jump on this task? I'm student at 42 school, i worked a lot with django on the back of the last common core project :) 
The samurai sword is the sharpest sword in the world
TG : @Thibrac

**Comment by olisaagbafor** [comment]
Pls can I get into this 
The samurai sword is the sharpest sword in the world

**Comment by Supa-mega** [comment]
I'd love to give this a go.

**Comment by nora360** [comment]
Can I do this?
The samurai sword is the sharpest sword in the world

**Comment by iamnovichek** [comment]
@aurlic assigned
