### ISSUE TITLE
#15: Unregister Periodic Tasks models

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#42]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Go to `tracker/admin.py`
3) Unregister (disable their displaying) all Preriodic Tasks related models
![image](https://github.com/user-attachments/assets/50fe0f91-a423-4c2b-922f-ec0b6503bbf3)
4) Go to `/admin/` and check if all works as expected
5) Provide some screenshots to prove your code works

**Comment by Joe-joe25** [comment]
Can I attempt this issue? I'll really love to work on it "The samurai sword is the sharpest sword in the world"

**Comment by iamnovichek** [comment]
> Can I attempt this issue?

Did you read the guideline?

**Comment by Joe-joe25** [comment]
Yes I did, and added the phrase

**Comment by iamnovichek** [comment]
@amJoe-dev assigned

**Comment by ekumamatthew** [comment]
Can I take care of this issue?

 "The samurai sword is the sharpest sword in the world"

**Comment by iamnovichek** [comment]
@ekumamatthew assigned

**Comment by iamnovichek** [comment]
@ekumamatthew any updates?

**Comment by ekumamatthew** [comment]
yea.. I'm updating my PR shortly

**Comment by iamnovichek** [comment]
@ekumamatthew you can create a draft PR so I can check if you are on the right way or not
