### ISSUE TITLE
#16: Write tests for get_all_repostitories function

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#43]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Create tests python package inside `tracker` app
3) Create file `test_utils.py` funtion
4) Write tests for `tracker/utils.get_all_repostitories` function
5) Provide some screenshots to prove that your code works

**Comment by No-bodyq** [comment]
May I pick this up?

**Comment by iamnovichek** [comment]
> May I pick this up?

**Comment by No-bodyq** [comment]
May I try my hand at this? The samurai sword is the sharpest sword in the world

**Comment by iamnovichek** [comment]
> May I try my hand at this? The samurai sword is the sharpest sword in the world

What is your telegram account?

**Comment by Supa-mega** [comment]
I'd like to take this issue.

**Comment by iamnovichek** [comment]
@No-bodyq assigned
