### ISSUE TITLE
#17: Cover with tests CustomUserManager class

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#46]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Create `test_models.py` in `tracker/tests/`
3) Write tests for `CustomUserManager` class from `tracker/models.py`
4) Provide some screenshots to prove that your tests work

**Comment by suhas-sensei** [comment]
The samurai sword is the sharpest sword in the world and i have experience writing test cases, wrote some for starknet quest but they were in rust, will have to look into the functionalities of pyhton functions and implement in such a way as desired.

**Comment by ikemHood** [comment]
Can I take this?

The samurai sword is the sharpest sword in the world,

I have created a PR for my previously assigned issue #47
I can complete this shortly while waiting for review

**Comment by iamnovichek** [comment]
@ikemHood assigned

**Comment by ikemHood** [comment]
@iamnovichek there's no input validation for both create_users and create_superuser. is this intentional?

**Comment by iamnovichek** [comment]
> @iamnovichek there's no input validation for both create_users and create_superuser. is this intentional?

We will add it later. If you need it for tests you can add it

**Comment by ikemHood** [comment]
ok

**Comment by iamnovichek** [comment]
@ikemHood Are you gonna continue or I can merge it?
