### ISSUE TITLE
#18: Write tests for get_user fucntion

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#47]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Write tests for `get_user` from `tracker/utils.py` in `tracker/tests/test_utils.py`
3) Provide some screenshots to prove that your tests work

**Comment by ikemHood** [comment]
Can I take this 
I would write test for the get_user function in utils,
The samurai sword is the sharpest sword in the world

**Comment by iamnovichek** [comment]
@ikemHood assigned
