### ISSUE TITLE
#19: Write tests for create_telegram_user function

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#48]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Write tests for `create_telegram_user` from `tracker/utils.py` in `tracker/tests/test_utils.py`
3) Provide some screenshots to prove that your tests work

**Comment by suhas-sensei** [comment]
The samurai sword is the sharpest sword in the world and i have experience writing test cases, wrote some for starknet quest but they were in rust, will have to look into the functionalities of pyhton functions and implement in such a way as desired.

**Comment by ikemHood** [comment]
I'd love to do this as well.
I would write test for the create_telegram_user function in utils,
The samurai sword is the sharpest sword in the world
ETA: <12hrs

**Comment by iamnovichek** [comment]
@suhas-sensei assigned

**Comment by suhas-sensei** [comment]
ty!

**Comment by iamnovichek** [comment]
@suhas-sensei any updates?

**Comment by suhas-sensei** [comment]
Yep, sending pr in 2hrs
