### ISSUE TITLE
#20: Write tests for check_issue_assignment_events function

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#49]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Write tests for `check_issue_assignment_events` from `tracker/utils.py` in `tracker/tests/test_utils.py`
3) Provide some screenshots to prove that your tests work

**Comment by raizo07** [comment]
Can I work on this? The samurai sword is the sharpest sword in the world.

**Comment by iamnovichek** [comment]
@raizo07 assigned
