### ISSUE TITLE
#21: Add contact support functionality 

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#53]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Add Django model `Support` with following fields: `user`,  `telegram_username` and update migrations
3) Create a function `get_support_link` in `tracker/utils.py` creates and returns a clickable link to support's DM
4) Add telegram button `Contact support` that provides a clickable link to support's DM for each repository
5) Provide some screenshots to prove that your feature works as expected

**Comment by ikemHood** [comment]
Can I handle this?
The samurai sword is the sharpest sword in the world

**Comment by 0xNgoo** [comment]
I'd love to give this a go.
The samurai sword is the sharpest sword in the world
EDT: 24hrs

**Comment by olisaagbafor** [comment]
Is this issue still available?
The samurai sword is the sharpest sword in the world

**Comment by iamnovichek** [comment]
@0xNgoo assigned

**Comment by 0xNgoo** [comment]
Thank you
