### ISSUE TITLE
#22: Cover with tests CustomUser model

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#57]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Write tests for `CustomUser` class from `tracker/models.py` in `tracker/tests/test_models.py`
3) Provide some screenshots to prove that your tests work

**Comment by mexes20** [comment]
Can I pick this? The samurai sword is the sharpest sword in the world.

**Comment by ekumamatthew** [comment]
I’d love to work on this task. 

The samurai sword is the sharpest sword in the world.

**Comment by iamnovichek** [comment]
@mexes20 assogned. Pls do it as fast as possible

**Comment by LawalRahman** [comment]
Can I take care of this issue?

**Comment by cryptogru725** [comment]
Can I work on this, please?
