### ISSUE TITLE
#23: Add Pylint workflow

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#64]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Create `.github/workflows/pylint.yml` file
3) Add workflow code to run `pylint` and check project's code quality

**Comment by raizo07** [comment]
@iamnovichek can I work on this 

The samurai sword is the sharpest sword in the world.
