### ISSUE TITLE
#1: Add guidelines access

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#7]
1) Create a branch named `feat/add-guidelines-access`
2) Add quick access to rules and FAQs (guidelines) button to our Telegram bot. Use GitHub API to fetch this data
3) Add "Get issue description" feature to out telegram bot

**Comment by VitalinaMykoliuk** [comment]
Hi! I'd like to take this task.

**Comment by djeck1432** [comment]
Go ahead
